// Generated by Viet Template M28.
// Source schema format: viet-template-contract-schema/1
// Schema version: 1
// Contract fingerprint: vt-contract:v1:f668af6bf9bca700a3d10e7ffc208debb7f9d442aa5c3d98aed616e783fbf9fa
// DO NOT EDIT.

export interface SimpleRecord {
  active: boolean;
  age: number;
  name: string | null;
}

export interface TemplateParameters {
  filter: SimpleRecord[] | null;
  items: SimpleRecord[] | null;
  tags: string[] | null;
}
