// Generated by Viet Template M28.
// Source schema format: viet-template-contract-schema/1
// Schema version: 1
// Contract fingerprint: vt-contract:v1:66125111cc9d7aba61f61caf428b25cb9c36010b6f6f4ad87ee9c47257e8b8ac
// DO NOT EDIT.

export interface SimpleRecord {
  active: boolean;
  age: number;
  name: string | null;
}

export interface TemplateParameters {
  order: SimpleRecord;
}
