// Generated by Viet Template M28.
// Source schema format: viet-template-contract-schema/1
// Schema version: 1
// Contract fingerprint: vt-contract:v1:7e046f289b39592313e016420c7309ad8e3b9c334cf2f75de91f4a72c6353dcd
// DO NOT EDIT.

export interface TemplateParameters {
  active: boolean;
  id: number;
  username: string;
}
