// Generated by Viet Template M28.
// Source schema format: viet-template-contract-schema/1
// Schema version: 1
// Contract fingerprint: vt-contract:v1:ed12fed18f2f66af912bc71da91f0ac1e0be276d5315ad77c27b49c1db39876f
// DO NOT EDIT.

export interface RecursiveNode {
  next: RecursiveNode | null;
  value: string | null;
}

export interface TemplateParameters {
  root: RecursiveNode;
}
