quarkus.viet-template.path=templates
quarkus.viet-template.suffix=.vtl
quarkus.viet-template.additional-suffixes=.html.vtl
quarkus.viet-template.runtime-compilation-enabled=false
quarkus.viet-template.undefined-reference-policy=SILENT
