package io.github.minh124199.viettemplate.tooling.gradle;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class VietTemplateGenerateTypeScriptTaskTest {

  private static GradleRunner createRunner(Path projectDir) {
    GradleRunner runner = GradleRunner.create().withProjectDir(projectDir.toFile());
    if (VietTemplateGenerateTypeScriptTaskTest.class
            .getClassLoader()
            .getResource("plugin-under-test-metadata.properties")
        != null) {
      return runner.withPluginClasspath();
    }
    List<File> cp =
        Arrays.stream(System.getProperty("java.class.path").split(File.pathSeparator))
            .map(File::new)
            .filter(File::exists)
            .collect(Collectors.toList());
    return runner.withGradleVersion("9.7.1").withPluginClasspath(cp);
  }

  @Test
  @DisplayName("Generates TypeScript declaration files (*.d.ts) via GradleRunner")
  void testGenerateVietTemplateTypeScript(@TempDir Path projectDir) throws Exception {
    Files.writeString(
        projectDir.resolve("settings.gradle.kts"),
        "rootProject.name = \"test-typescript-project\"\n",
        StandardCharsets.UTF_8);

    Files.writeString(
        projectDir.resolve("build.gradle.kts"),
        "plugins {\n"
            + "    java\n"
            + "    id(\"io.github.minh124199.viet-template\")\n"
            + "}\n"
            + "repositories {\n"
            + "    mavenCentral()\n"
            + "}\n",
        StandardCharsets.UTF_8);

    Path templateDir = projectDir.resolve("src/main/viet-template");
    Files.createDirectories(templateDir);
    Files.writeString(
        templateDir.resolve("order-view.vtl"),
        "Order #$orderId for $customer",
        StandardCharsets.UTF_8);
    Files.writeString(
        templateDir.resolve("order-view.vtl.contract"),
        "orderId=long\ncustomer=String\n",
        StandardCharsets.UTF_8);

    BuildResult result =
        createRunner(projectDir)
            .withArguments(VietTemplatePlugin.GENERATE_TYPESCRIPT_TASK_NAME)
            .build();

    assertThat(result.task(":" + VietTemplatePlugin.GENERATE_SCHEMAS_TASK_NAME)).isNotNull();
    assertThat(result.task(":" + VietTemplatePlugin.GENERATE_TYPESCRIPT_TASK_NAME)).isNotNull();
    assertThat(result.task(":" + VietTemplatePlugin.GENERATE_TYPESCRIPT_TASK_NAME).getOutcome())
        .isEqualTo(TaskOutcome.SUCCESS);

    Path dtsFile = projectDir.resolve("build/generated/viet-template/typescript/order-view.d.ts");
    assertThat(dtsFile).isRegularFile();
    String dts = Files.readString(dtsFile, StandardCharsets.UTF_8);
    assertThat(dts).contains("// Generated by Viet Template M28.");
    assertThat(dts).contains("export interface TemplateParameters {");
    assertThat(dts).contains("customer: string;");
    assertThat(dts).contains("orderId: number;");
  }

  @Test
  @DisplayName("Skips gracefully when no schemas exist")
  void testSkipWhenNoSchemas(@TempDir Path projectDir) throws Exception {
    Files.writeString(
        projectDir.resolve("settings.gradle.kts"),
        "rootProject.name = \"test-empty-project\"\n",
        StandardCharsets.UTF_8);

    Files.writeString(
        projectDir.resolve("build.gradle.kts"),
        "plugins {\n"
            + "    java\n"
            + "    id(\"io.github.minh124199.viet-template\")\n"
            + "}\n"
            + "repositories {\n"
            + "    mavenCentral()\n"
            + "}\n",
        StandardCharsets.UTF_8);

    Path templateDir = projectDir.resolve("src/main/viet-template");
    Files.createDirectories(templateDir);

    BuildResult result =
        createRunner(projectDir)
            .withArguments(VietTemplatePlugin.GENERATE_TYPESCRIPT_TASK_NAME)
            .build();

    assertThat(result.task(":" + VietTemplatePlugin.GENERATE_TYPESCRIPT_TASK_NAME)).isNotNull();
    assertThat(result.task(":" + VietTemplatePlugin.GENERATE_TYPESCRIPT_TASK_NAME).getOutcome())
        .isEqualTo(TaskOutcome.SUCCESS);

    Path tsDir = projectDir.resolve("build/generated/viet-template/typescript");
    if (Files.exists(tsDir)) {
      assertThat(tsDir).isEmptyDirectory();
    }
  }
}
