quarkus.application.name=quarkus-frontend-dev-mode-e2e
quarkus.analytics.disabled=true
quarkus.http.port=0
quarkus.http.host=127.0.0.1

# Viet Template dev configuration
quarkus.viet-template.path=templates
quarkus.viet-template.suffix=.vtl
quarkus.viet-template.runtime-compilation-enabled=true

# Frontend assets development mode
quarkus.viet-template.assets.enabled=true
quarkus.viet-template.assets.mode=development
quarkus.viet-template.assets.dev-server=http://127.0.0.1:5173
