viet-template.runtime-compilation-enabled=true
viet-template.cache=false
viet-template.check-template-location=true
viet-template.suffix=.vtl
viet-template.order=1
spring.main.banner-mode=off
spring.devtools.restart.trigger-file=.restart-trigger
spring.devtools.restart.poll-interval=200ms
spring.devtools.restart.quiet-period=100ms
logging.level.org.springframework.boot.devtools=DEBUG

