spring.application.name=spring-frontend-e2e
server.port=0

# Viet Template configuration
viet-template.runtime-compilation-enabled=false
viet-template.check-template-location=true
viet-template.suffix=.vtl
viet-template.order=1

# Frontend asset integration configuration
viet-template.assets.enabled=true
viet-template.assets.mode=production
viet-template.assets.public-base=/
viet-template.assets.module-preload=true
viet-template.assets.manifest-location=classpath:/static/.vite/manifest.json

# Static web resources
spring.web.resources.static-locations=classpath:/static/
