<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.minh124199.test</groupId>
    <artifactId>aot-maven-failure</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <viet-template.version>1.0.0-RC2</viet-template.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.minh124199</groupId>
            <artifactId>viet-template-api</artifactId>
            <version>${viet-template.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.minh124199</groupId>
            <artifactId>viet-template-runtime</artifactId>
            <version>${viet-template.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.minh124199</groupId>
            <artifactId>viet-template-vtl-interpreter</artifactId>
            <version>${viet-template.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.github.minh124199</groupId>
                <artifactId>viet-template-maven-plugin</artifactId>
                <version>${viet-template.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
