#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "=== Viet Template AOT Tooling Dual-Build Parity Verification ==="

# Step 1: Run Maven basic fixture (compiles with maven-plugin, tests runtime execution without .vtl)
echo "[STEP 1] Running maven-basic consumer fixture..."
"${ROOT_DIR}/mvnw" clean test -f "${ROOT_DIR}/integration-tests/aot/maven-basic/pom.xml" -B

# Step 2: Run Gradle basic fixture (compiles with gradle-plugin, tests runtime execution without .vtl)
echo "[STEP 2] Running gradle-basic consumer fixture..."
"${ROOT_DIR}/gradlew" clean test --project-dir "${ROOT_DIR}/integration-tests/aot/gradle-basic" --no-daemon

# Step 3: Compare templates.idx between Maven and Gradle
echo "[STEP 3] Comparing templates.idx byte-for-byte parity..."
MAVEN_IDX="${ROOT_DIR}/integration-tests/aot/maven-basic/target/classes/META-INF/viet-template/templates.idx"
GRADLE_IDX="${ROOT_DIR}/integration-tests/aot/gradle-basic/build/generated/viet-template/resources/META-INF/viet-template/templates.idx"

if ! cmp -s "${MAVEN_IDX}" "${GRADLE_IDX}"; then
    echo "[FAIL] templates.idx differs between Maven and Gradle:"
    diff -u "${MAVEN_IDX}" "${GRADLE_IDX}"
    exit 1
fi
echo "[PASS] templates.idx matches identically."

# Step 4: Compare generated .class files byte-for-byte
echo "[STEP 4] Comparing generated bytecode (.class files) parity..."
MAVEN_CLASSES="${ROOT_DIR}/integration-tests/aot/maven-basic/target/classes/io/github/minh124199/viettemplate/generated"
GRADLE_CLASSES="${ROOT_DIR}/integration-tests/aot/gradle-basic/build/generated/viet-template/classes/io/github/minh124199/viettemplate/generated"

for maven_class in "${MAVEN_CLASSES}"/*.class; do
    class_name="$(basename "${maven_class}")"
    gradle_class="${GRADLE_CLASSES}/${class_name}"
    if [ ! -f "${gradle_class}" ]; then
        echo "[FAIL] Class ${class_name} generated by Maven but missing in Gradle!"
        exit 1
    fi
    if ! cmp -s "${maven_class}" "${gradle_class}"; then
        echo "[FAIL] Bytecode mismatch for ${class_name} between Maven and Gradle!"
        exit 1
    fi
    echo "[PASS] Bytecode identical for ${class_name}"
done

# Step 5: Verify Java 21 bytecode version (major version 65)
echo "[STEP 5] Verifying classfile version 65 (Java 21)..."
for class_file in "${MAVEN_CLASSES}"/*.class; do
    python3 -c "
import sys
with open('${class_file}', 'rb') as f:
    magic = f.read(4)
    if magic != b'\xca\xfe\xba\xbe':
        sys.exit(1)
    minor = int.from_bytes(f.read(2), 'big')
    major = int.from_bytes(f.read(2), 'big')
    if major != 65:
        sys.exit(2)
"
    STATUS=$?
    if [ ${STATUS} -ne 0 ]; then
        echo "[FAIL] Class ${class_file} is not a valid Java 21 classfile (version 65)!"
        exit 1
    fi
done
echo "[PASS] All generated bytecode files are valid classfile version 65 (Java 21)."

# Step 6: Verify Maven failure diagnostics
echo "[STEP 6] Verifying maven-failure diagnostic reporting..."
set +e
MAVEN_FAIL_OUT=$("${ROOT_DIR}/mvnw" process-classes -f "${ROOT_DIR}/integration-tests/aot/maven-failure/pom.xml" -B 2>&1)
MAVEN_STATUS=$?
set -e
if [ ${MAVEN_STATUS} -eq 0 ]; then
    echo "[FAIL] maven-failure was expected to fail but succeeded!"
    exit 1
fi
if ! echo "${MAVEN_FAIL_OUT}" | grep -q "invalid.vtl:3:1 \[PARSER:UNCLOSED_DIRECTIVE\]"; then
    echo "[FAIL] maven-failure did not report expected line:column diagnostic! Output:"
    echo "${MAVEN_FAIL_OUT}"
    exit 1
fi
echo "[PASS] Maven correctly failed with line:column syntax diagnostic."

# Step 7: Verify Gradle failure diagnostics
echo "[STEP 7] Verifying gradle-failure diagnostic reporting..."
set +e
GRADLE_FAIL_OUT=$("${ROOT_DIR}/gradlew" compileVietTemplates --project-dir "${ROOT_DIR}/integration-tests/aot/gradle-failure" --no-daemon 2>&1)
GRADLE_STATUS=$?
set -e
if [ ${GRADLE_STATUS} -eq 0 ]; then
    echo "[FAIL] gradle-failure was expected to fail but succeeded!"
    exit 1
fi
if ! echo "${GRADLE_FAIL_OUT}" | grep -q "invalid.vtl:3:1 \[PARSER:UNCLOSED_DIRECTIVE\]"; then
    echo "[FAIL] gradle-failure did not report expected line:column diagnostic! Output:"
    echo "${GRADLE_FAIL_OUT}"
    exit 1
fi
echo "[PASS] Gradle correctly failed with line:column syntax diagnostic."

echo ""
echo "[SUCCESS] AOT Tooling Dual-Build Parity & Verification PASSED across all fixtures!"
exit 0
