#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "=== Viet Template Spring Boot AOT Integration & Parity Verification ==="

APP_PID=""
cleanup() {
    if [ -n "${APP_PID}" ] && kill -0 "${APP_PID}" 2>/dev/null; then
        kill -9 "${APP_PID}" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

wait_for_server() {
    local port="$1"
    local max_wait=30
    local count=0
    while ! curl -s "http://localhost:${port}/hello" >/dev/null 2>&1; do
        sleep 1
        count=$((count + 1))
        if [ "${count}" -ge "${max_wait}" ]; then
            echo "[FAIL] Server on port ${port} failed to start within ${max_wait}s!"
            return 1
        fi
    done
    return 0
}

# Step 1: Run Maven Spring Boot AOT fixture tests
echo "[STEP 1] Running maven-mvc-aot consumer fixture tests..."
"${ROOT_DIR}/mvnw" clean test -f "${ROOT_DIR}/integration-tests/spring/maven-mvc-aot/pom.xml" -B
echo "[PASS] Maven Spring Boot AOT fixture tests passed."

# Step 2: Run Gradle Spring Boot AOT fixture tests
echo "[STEP 2] Running gradle-mvc-aot consumer fixture tests..."
"${ROOT_DIR}/gradlew" clean test --project-dir "${ROOT_DIR}/integration-tests/spring/gradle-mvc-aot" --no-daemon
echo "[PASS] Gradle Spring Boot AOT fixture tests passed."

# Step 3: Compare templates.idx between Maven and Gradle
echo "[STEP 3] Comparing templates.idx byte-for-byte parity..."
MAVEN_IDX="${ROOT_DIR}/integration-tests/spring/maven-mvc-aot/target/classes/META-INF/viet-template/templates.idx"
GRADLE_IDX="${ROOT_DIR}/integration-tests/spring/gradle-mvc-aot/build/generated/viet-template/resources/META-INF/viet-template/templates.idx"

if ! cmp -s "${MAVEN_IDX}" "${GRADLE_IDX}"; then
    echo "[FAIL] templates.idx differs between Maven and Gradle:"
    diff -u "${MAVEN_IDX}" "${GRADLE_IDX}"
    exit 1
fi
echo "[PASS] templates.idx matches identically."

# Step 4: Compare generated .class files byte-for-byte
echo "[STEP 4] Comparing generated bytecode (.class files) parity..."
MAVEN_CLASSES="${ROOT_DIR}/integration-tests/spring/maven-mvc-aot/target/classes/io/github/minh124199/viettemplate/generated"
GRADLE_CLASSES="${ROOT_DIR}/integration-tests/spring/gradle-mvc-aot/build/generated/viet-template/classes/io/github/minh124199/viettemplate/generated"

for maven_class in "${MAVEN_CLASSES}"/*.class; do
    class_name="$(basename "${maven_class}")"
    gradle_class="${GRADLE_CLASSES}/${class_name}"
    if [ ! -f "${gradle_class}" ]; then
        echo "[FAIL] Class ${class_name} generated by Maven but missing in Gradle!"
        exit 1
    fi
    if ! cmp -s "${maven_class}" "${gradle_class}"; then
        echo "[FAIL] Bytecode mismatch for ${class_name} between Maven and Gradle!"
        exit 1
    fi
    echo "[PASS] Bytecode identical for ${class_name}"
done

# Step 5: Verify Java 17 bytecode version (major version 61)
echo "[STEP 5] Verifying classfile version 61 (Java 17)..."
for class_file in "${MAVEN_CLASSES}"/*.class; do
    python3 -c "
import sys
with open('${class_file}', 'rb') as f:
    magic = f.read(4)
    if magic != b'\xca\xfe\xba\xbe':
        sys.exit(1)
    minor = int.from_bytes(f.read(2), 'big')
    major = int.from_bytes(f.read(2), 'big')
    if major != 61:
        sys.exit(2)
"
    STATUS=$?
    if [ ${STATUS} -ne 0 ]; then
        echo "[FAIL] Class ${class_file} is not a valid Java 17 classfile (version 61)!"
        exit 1
    fi
done
echo "[PASS] All generated bytecode files are valid classfile version 61 (Java 17)."

# Step 6: Build packaged boot JARs
echo "[STEP 6] Building packaged Spring Boot JARs..."
"${ROOT_DIR}/mvnw" package -DskipTests -f "${ROOT_DIR}/integration-tests/spring/maven-mvc-aot/pom.xml" -B
"${ROOT_DIR}/gradlew" bootJar --project-dir "${ROOT_DIR}/integration-tests/spring/gradle-mvc-aot" --no-daemon

MAVEN_JAR="${ROOT_DIR}/integration-tests/spring/maven-mvc-aot/target/spring-maven-mvc-aot-1.0.0.jar"
GRADLE_JAR="${ROOT_DIR}/integration-tests/spring/gradle-mvc-aot/build/libs/spring-gradle-mvc-aot-1.0.0.jar"

if [ ! -f "${MAVEN_JAR}" ]; then
    echo "[FAIL] Maven packaged JAR not found: ${MAVEN_JAR}"
    exit 1
fi
if [ ! -f "${GRADLE_JAR}" ]; then
    echo "[FAIL] Gradle packaged JAR not found: ${GRADLE_JAR}"
    exit 1
fi
echo "[PASS] Both packaged Spring Boot JARs built successfully."

# Step 7: Inspect JAR contents
echo "[STEP 7] Inspecting JAR contents..."
for jar_file in "${MAVEN_JAR}" "${GRADLE_JAR}"; do
    jar_name="$(basename "${jar_file}")"
    echo "  Inspecting ${jar_name}..."

    # Verify templates.idx exists
    if ! jar tf "${jar_file}" | grep -q "templates\.idx"; then
        echo "[FAIL] templates.idx missing from ${jar_name}!"
        exit 1
    fi

    # Verify generated classes exist
    if ! jar tf "${jar_file}" | grep -q "T_hello_vtl"; then
        echo "[FAIL] Generated class T_hello_vtl missing from ${jar_name}!"
        exit 1
    fi
    if ! jar tf "${jar_file}" | grep -q "T_users_vtl"; then
        echo "[FAIL] Generated class T_users_vtl missing from ${jar_name}!"
        exit 1
    fi

    # Verify source .vtl files are absent
    if jar tf "${jar_file}" | grep -q "\.vtl$"; then
        echo "[FAIL] Source .vtl files found in ${jar_name} runtime package!"
        exit 1
    fi

    echo "  [PASS] ${jar_name} has generated classes, templates.idx, and NO source .vtl files."
done

# Step 8: Verify executable Maven Boot JAR
echo "[STEP 8] Verifying executable Maven Boot JAR runtime execution..."
MAVEN_PORT=18090
java -jar "${MAVEN_JAR}" --server.port="${MAVEN_PORT}" > /tmp/maven-boot-jar.log 2>&1 &
APP_PID=$!

wait_for_server "${MAVEN_PORT}"

MAVEN_HTTP_CODE=$(curl -s -o /tmp/maven-response.html -w "%{http_code}" "http://localhost:${MAVEN_PORT}/hello?name=MavenUser&location=Hanoi")
if [ "${MAVEN_HTTP_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 from Maven JAR, got ${MAVEN_HTTP_CODE}!"
    cat /tmp/maven-boot-jar.log
    exit 1
fi

if ! grep -q "<h1>Hello, MavenUser!</h1>" /tmp/maven-response.html; then
    echo "[FAIL] Response body missing expected greeting from Maven JAR:"
    cat /tmp/maven-response.html
    exit 1
fi
if ! grep -q "<p>Welcome to Hanoi.</p>" /tmp/maven-response.html; then
    echo "[FAIL] Response body missing expected location from Maven JAR:"
    cat /tmp/maven-response.html
    exit 1
fi

kill -9 "${APP_PID}" 2>/dev/null || true
wait "${APP_PID}" 2>/dev/null || true
APP_PID=""
echo "[PASS] Maven executable JAR served HTTP 200 HTML with pure AOT execution."

# Step 9: Verify executable Gradle Boot JAR
echo "[STEP 9] Verifying executable Gradle Boot JAR runtime execution..."
GRADLE_PORT=18091
java -jar "${GRADLE_JAR}" --server.port="${GRADLE_PORT}" > /tmp/gradle-boot-jar.log 2>&1 &
APP_PID=$!

wait_for_server "${GRADLE_PORT}"

GRADLE_HTTP_CODE=$(curl -s -o /tmp/gradle-response.html -w "%{http_code}" "http://localhost:${GRADLE_PORT}/hello?name=GradleUser&location=Saigon")
if [ "${GRADLE_HTTP_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 from Gradle JAR, got ${GRADLE_HTTP_CODE}!"
    cat /tmp/gradle-boot-jar.log
    exit 1
fi

if ! grep -q "<h1>Hello, GradleUser!</h1>" /tmp/gradle-response.html; then
    echo "[FAIL] Response body missing expected greeting from Gradle JAR:"
    cat /tmp/gradle-response.html
    exit 1
fi
if ! grep -q "<p>Welcome to Saigon.</p>" /tmp/gradle-response.html; then
    echo "[FAIL] Response body missing expected location from Gradle JAR:"
    cat /tmp/gradle-response.html
    exit 1
fi

kill -9 "${APP_PID}" 2>/dev/null || true
wait "${APP_PID}" 2>/dev/null || true
APP_PID=""
echo "[PASS] Gradle executable JAR served HTTP 200 HTML with pure AOT execution."

echo ""
echo "[SUCCESS] Spring Boot MVC AOT Dual-Build Parity & Verification PASSED across all fixtures!"
exit 0
