#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "=== Viet Template Spring Framework 7 / Spring Boot 4 / Spring Security 7 Integration & Parity Verification ==="

APP_PID=""
cleanup() {
    if [ -n "${APP_PID}" ] && kill -0 "${APP_PID}" 2>/dev/null; then
        kill -9 "${APP_PID}" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

wait_for_server() {
    local port="$1"
    local max_wait=30
    local count=0
    while ! curl -s "http://localhost:${port}/public" >/dev/null 2>&1; do
        sleep 1
        count=$((count + 1))
        if [ "${count}" -ge "${max_wait}" ]; then
            echo "[FAIL] Server on port ${port} failed to start within ${max_wait}s!"
            return 1
        fi
    done
    return 0
}

# Step 1: Run Maven Spring Boot 4 / Security 7 fixture tests
echo "[STEP 1] Running maven-security7-aot consumer fixture tests..."
"${ROOT_DIR}/mvnw" clean test -f "${ROOT_DIR}/integration-tests/spring/maven-security7-aot/pom.xml" -B
echo "[PASS] Maven Spring Boot 4 / Security 7 fixture tests passed."

# Step 2: Run Gradle Spring Boot 4 / Security 7 fixture tests
echo "[STEP 2] Running gradle-security7-aot consumer fixture tests..."
"${ROOT_DIR}/gradlew" clean test --project-dir "${ROOT_DIR}/integration-tests/spring/gradle-security7-aot" --no-daemon
echo "[PASS] Gradle Spring Boot 4 / Security 7 fixture tests passed."

# Step 3: Compare templates.idx between Maven and Gradle
echo "[STEP 3] Comparing templates.idx byte-for-byte parity..."
MAVEN_IDX="${ROOT_DIR}/integration-tests/spring/maven-security7-aot/target/classes/META-INF/viet-template/templates.idx"
GRADLE_IDX="${ROOT_DIR}/integration-tests/spring/gradle-security7-aot/build/generated/viet-template/resources/META-INF/viet-template/templates.idx"

if ! cmp -s "${MAVEN_IDX}" "${GRADLE_IDX}"; then
    echo "[FAIL] templates.idx differs between Maven and Gradle:"
    diff -u "${MAVEN_IDX}" "${GRADLE_IDX}"
    exit 1
fi
echo "[PASS] templates.idx matches identically."

# Step 4: Compare generated .class files byte-for-byte
echo "[STEP 4] Comparing generated bytecode (.class files) parity..."
MAVEN_CLASSES="${ROOT_DIR}/integration-tests/spring/maven-security7-aot/target/classes/io/github/minh124199/viettemplate/generated"
GRADLE_CLASSES="${ROOT_DIR}/integration-tests/spring/gradle-security7-aot/build/generated/viet-template/classes/io/github/minh124199/viettemplate/generated"

for maven_class in "${MAVEN_CLASSES}"/*.class; do
    class_name="$(basename "${maven_class}")"
    gradle_class="${GRADLE_CLASSES}/${class_name}"
    if [ ! -f "${gradle_class}" ]; then
        echo "[FAIL] Class ${class_name} generated by Maven but missing in Gradle!"
        exit 1
    fi
    if ! cmp -s "${maven_class}" "${gradle_class}"; then
        echo "[FAIL] Bytecode mismatch for ${class_name} between Maven and Gradle!"
        exit 1
    fi
    echo "[PASS] Bytecode identical for ${class_name}"
done

# Step 5: Verify Java 17 bytecode version (major version 61)
echo "[STEP 5] Verifying classfile version 61 (Java 17)..."
for class_file in "${MAVEN_CLASSES}"/*.class; do
    python3 -c "
import sys
with open('${class_file}', 'rb') as f:
    magic = f.read(4)
    if magic != b'\xca\xfe\xba\xbe':
        sys.exit(1)
    minor = int.from_bytes(f.read(2), 'big')
    major = int.from_bytes(f.read(2), 'big')
    if major != 61:
        sys.exit(2)
"
    STATUS=$?
    if [ ${STATUS} -ne 0 ]; then
        echo "[FAIL] Class ${class_file} is not a valid Java 17 classfile (version 61)!"
        exit 1
    fi
done
echo "[PASS] All generated bytecode files are valid classfile version 61 (Java 17)."

# Step 6: Build packaged boot JARs
echo "[STEP 6] Building packaged Spring Boot 4 JARs..."
"${ROOT_DIR}/mvnw" package -DskipTests -f "${ROOT_DIR}/integration-tests/spring/maven-security7-aot/pom.xml" -B
"${ROOT_DIR}/gradlew" bootJar --project-dir "${ROOT_DIR}/integration-tests/spring/gradle-security7-aot" --no-daemon

MAVEN_JAR="${ROOT_DIR}/integration-tests/spring/maven-security7-aot/target/spring-maven-security7-aot-1.0.0.jar"
GRADLE_JAR="${ROOT_DIR}/integration-tests/spring/gradle-security7-aot/build/libs/spring-gradle-security7-aot-1.0.0.jar"

if [ ! -f "${MAVEN_JAR}" ]; then
    echo "[FAIL] Maven packaged JAR not found: ${MAVEN_JAR}"
    exit 1
fi
if [ ! -f "${GRADLE_JAR}" ]; then
    echo "[FAIL] Gradle packaged JAR not found: ${GRADLE_JAR}"
    exit 1
fi
echo "[PASS] Both packaged Spring Boot 4 JARs built successfully."

# Step 7: Inspect JAR contents
echo "[STEP 7] Inspecting JAR contents..."
for jar_file in "${MAVEN_JAR}" "${GRADLE_JAR}"; do
    jar_name="$(basename "${jar_file}")"
    echo "  Inspecting ${jar_name}..."

    # Verify templates.idx exists
    if ! jar tf "${jar_file}" | grep -q "templates\.idx"; then
        echo "[FAIL] templates.idx missing from ${jar_name}!"
        exit 1
    fi

    # Verify generated classes exist
    if ! jar tf "${jar_file}" | grep -q "T_dashboard_vtl"; then
        echo "[FAIL] Generated class T_dashboard_vtl missing from ${jar_name}!"
        exit 1
    fi
    if ! jar tf "${jar_file}" | grep -q "T_public_vtl"; then
        echo "[FAIL] Generated class T_public_vtl missing from ${jar_name}!"
        exit 1
    fi

    # Verify source .vtl files are absent
    if jar tf "${jar_file}" | grep -q "\.vtl$"; then
        echo "[FAIL] Source .vtl files found in ${jar_name} runtime package!"
        exit 1
    fi

    echo "  [PASS] ${jar_name} has generated classes, templates.idx, and NO source .vtl files."
done

# Step 8: Verify executable Maven Boot 4 JAR runtime execution
echo "[STEP 8] Verifying executable Maven Boot 4 JAR runtime execution..."
MAVEN_PORT=18096
java -jar "${MAVEN_JAR}" --server.port="${MAVEN_PORT}" > /tmp/maven-security7-boot-jar.log 2>&1 &
APP_PID=$!

wait_for_server "${MAVEN_PORT}"

# Anonymous access to /public
MAVEN_PUB_CODE=$(curl -s -o /tmp/maven-sec7-pub.html -w "%{http_code}" "http://localhost:${MAVEN_PORT}/public")
if [ "${MAVEN_PUB_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 from Maven JAR on /public, got ${MAVEN_PUB_CODE}!"
    cat /tmp/maven-security7-boot-jar.log
    exit 1
fi
if ! grep -q "<h1>Public Page</h1>" /tmp/maven-sec7-pub.html; then
    echo "[FAIL] Missing Public Page heading from Maven JAR:"
    cat /tmp/maven-sec7-pub.html
    exit 1
fi
if ! grep -q "Browsing anonymously" /tmp/maven-sec7-pub.html; then
    echo "[FAIL] Missing Browsing anonymously indicator from Maven JAR:"
    cat /tmp/maven-sec7-pub.html
    exit 1
fi

# Anonymous access to protected /admin
MAVEN_UNAUTH_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${MAVEN_PORT}/admin")
if [ "${MAVEN_UNAUTH_CODE}" != "401" ]; then
    echo "[FAIL] Expected HTTP 401 on unauthenticated /admin, got ${MAVEN_UNAUTH_CODE}!"
    exit 1
fi

# Alice authenticated access to /dashboard (ROLE_USER, ROLE_ADMIN)
MAVEN_ALICE_CODE=$(curl -s -u alice:password -o /tmp/maven-sec7-alice.html -w "%{http_code}" "http://localhost:${MAVEN_PORT}/dashboard")
if [ "${MAVEN_ALICE_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 for Alice on /dashboard, got ${MAVEN_ALICE_CODE}!"
    exit 1
fi
if ! grep -q "<h1>Welcome, alice!</h1>" /tmp/maven-sec7-alice.html; then
    echo "[FAIL] Missing Welcome, alice! from Maven JAR:"
    cat /tmp/maven-sec7-alice.html
    exit 1
fi
if ! grep -q "Admin Access Granted" /tmp/maven-sec7-alice.html; then
    echo "[FAIL] Missing Admin Access Granted for Alice from Maven JAR:"
    cat /tmp/maven-sec7-alice.html
    exit 1
fi
if ! grep -q "User Access Granted" /tmp/maven-sec7-alice.html; then
    echo "[FAIL] Missing User Access Granted for Alice from Maven JAR:"
    cat /tmp/maven-sec7-alice.html
    exit 1
fi
if ! grep -q 'name="_csrf"' /tmp/maven-sec7-alice.html; then
    echo "[FAIL] Missing CSRF input token for Alice from Maven JAR:"
    cat /tmp/maven-sec7-alice.html
    exit 1
fi

# Bob authenticated access to /dashboard (ROLE_USER only)
MAVEN_BOB_CODE=$(curl -s -u bob:password -o /tmp/maven-sec7-bob.html -w "%{http_code}" "http://localhost:${MAVEN_PORT}/dashboard")
if [ "${MAVEN_BOB_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 for Bob on /dashboard, got ${MAVEN_BOB_CODE}!"
    exit 1
fi
if ! grep -q "<h1>Welcome, bob!</h1>" /tmp/maven-sec7-bob.html; then
    echo "[FAIL] Missing Welcome, bob! from Maven JAR:"
    cat /tmp/maven-sec7-bob.html
    exit 1
fi
if grep -q "Admin Access Granted" /tmp/maven-sec7-bob.html; then
    echo "[FAIL] Unexpected Admin Access Granted for Bob from Maven JAR:"
    cat /tmp/maven-sec7-bob.html
    exit 1
fi
if ! grep -q "User Access Granted" /tmp/maven-sec7-bob.html; then
    echo "[FAIL] Missing User Access Granted for Bob from Maven JAR:"
    cat /tmp/maven-sec7-bob.html
    exit 1
fi

# Bob forbidden access to /admin (lacks ROLE_ADMIN)
MAVEN_FORBID_CODE=$(curl -s -u bob:password -o /dev/null -w "%{http_code}" "http://localhost:${MAVEN_PORT}/admin")
if [ "${MAVEN_FORBID_CODE}" != "403" ]; then
    echo "[FAIL] Expected HTTP 403 for Bob on /admin, got ${MAVEN_FORBID_CODE}!"
    exit 1
fi

kill -9 "${APP_PID}" 2>/dev/null || true
wait "${APP_PID}" 2>/dev/null || true
APP_PID=""
echo "[PASS] Maven executable JAR served HTTP 200/401/403 with pure AOT execution and Spring Security 7 enforcement."

# Step 9: Verify executable Gradle Boot 4 JAR runtime execution
echo "[STEP 9] Verifying executable Gradle Boot 4 JAR runtime execution..."
GRADLE_PORT=18097
java -jar "${GRADLE_JAR}" --server.port="${GRADLE_PORT}" > /tmp/gradle-security7-boot-jar.log 2>&1 &
APP_PID=$!

wait_for_server "${GRADLE_PORT}"

# Anonymous access to /public
GRADLE_PUB_CODE=$(curl -s -o /tmp/gradle-sec7-pub.html -w "%{http_code}" "http://localhost:${GRADLE_PORT}/public")
if [ "${GRADLE_PUB_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 from Gradle JAR on /public, got ${GRADLE_PUB_CODE}!"
    cat /tmp/gradle-security7-boot-jar.log
    exit 1
fi
if ! grep -q "<h1>Public Page</h1>" /tmp/gradle-sec7-pub.html; then
    echo "[FAIL] Missing Public Page heading from Gradle JAR:"
    cat /tmp/gradle-sec7-pub.html
    exit 1
fi
if ! grep -q "Browsing anonymously" /tmp/gradle-sec7-pub.html; then
    echo "[FAIL] Missing Browsing anonymously indicator from Gradle JAR:"
    cat /tmp/gradle-sec7-pub.html
    exit 1
fi

# Anonymous access to protected /admin
GRADLE_UNAUTH_CODE=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${GRADLE_PORT}/admin")
if [ "${GRADLE_UNAUTH_CODE}" != "401" ]; then
    echo "[FAIL] Expected HTTP 401 on unauthenticated /admin, got ${GRADLE_UNAUTH_CODE}!"
    exit 1
fi

# Alice authenticated access to /dashboard (ROLE_USER, ROLE_ADMIN)
GRADLE_ALICE_CODE=$(curl -s -u alice:password -o /tmp/gradle-sec7-alice.html -w "%{http_code}" "http://localhost:${GRADLE_PORT}/dashboard")
if [ "${GRADLE_ALICE_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 for Alice on /dashboard, got ${GRADLE_ALICE_CODE}!"
    exit 1
fi
if ! grep -q "<h1>Welcome, alice!</h1>" /tmp/gradle-sec7-alice.html; then
    echo "[FAIL] Missing Welcome, alice! from Gradle JAR:"
    cat /tmp/gradle-sec7-alice.html
    exit 1
fi
if ! grep -q "Admin Access Granted" /tmp/gradle-sec7-alice.html; then
    echo "[FAIL] Missing Admin Access Granted for Alice from Gradle JAR:"
    cat /tmp/gradle-sec7-alice.html
    exit 1
fi
if ! grep -q "User Access Granted" /tmp/gradle-sec7-alice.html; then
    echo "[FAIL] Missing User Access Granted for Alice from Gradle JAR:"
    cat /tmp/gradle-sec7-alice.html
    exit 1
fi
if ! grep -q 'name="_csrf"' /tmp/gradle-sec7-alice.html; then
    echo "[FAIL] Missing CSRF input token for Alice from Gradle JAR:"
    cat /tmp/gradle-sec7-alice.html
    exit 1
fi

# Bob authenticated access to /dashboard (ROLE_USER only)
GRADLE_BOB_CODE=$(curl -s -u bob:password -o /tmp/gradle-sec7-bob.html -w "%{http_code}" "http://localhost:${GRADLE_PORT}/dashboard")
if [ "${GRADLE_BOB_CODE}" != "200" ]; then
    echo "[FAIL] Expected HTTP 200 for Bob on /dashboard, got ${GRADLE_BOB_CODE}!"
    exit 1
fi
if ! grep -q "<h1>Welcome, bob!</h1>" /tmp/gradle-sec7-bob.html; then
    echo "[FAIL] Missing Welcome, bob! from Gradle JAR:"
    cat /tmp/gradle-sec7-bob.html
    exit 1
fi
if grep -q "Admin Access Granted" /tmp/gradle-sec7-bob.html; then
    echo "[FAIL] Unexpected Admin Access Granted for Bob from Gradle JAR:"
    cat /tmp/gradle-sec7-bob.html
    exit 1
fi
if ! grep -q "User Access Granted" /tmp/gradle-sec7-bob.html; then
    echo "[FAIL] Missing User Access Granted for Bob from Gradle JAR:"
    cat /tmp/gradle-sec7-bob.html
    exit 1
fi

# Bob forbidden access to /admin (lacks ROLE_ADMIN)
GRADLE_FORBID_CODE=$(curl -s -u bob:password -o /dev/null -w "%{http_code}" "http://localhost:${GRADLE_PORT}/admin")
if [ "${GRADLE_FORBID_CODE}" != "403" ]; then
    echo "[FAIL] Expected HTTP 403 for Bob on /admin, got ${GRADLE_FORBID_CODE}!"
    exit 1
fi

kill -9 "${APP_PID}" 2>/dev/null || true
wait "${APP_PID}" 2>/dev/null || true
APP_PID=""
echo "[PASS] Gradle executable JAR served HTTP 200/401/403 with pure AOT execution and Spring Security 7 enforcement."

echo ""
echo "[SUCCESS] Spring Framework 7 / Spring Boot 4 / Spring Security 7 Dual-Build Parity & Verification PASSED!"
exit 0
