#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "=== Viet Template GraalVM Native Image & Spring AOT Verification ==="

GRAALVM_DIR="${GRAALVM_HOME:-}"
if [ -z "${GRAALVM_DIR}" ]; then
    if command -v native-image >/dev/null 2>&1; then
        GRAALVM_DIR="$(dirname "$(dirname "$(command -v native-image)")")"
    else
        for candidate in \
            "${HOME:-}/opt"/graalvm-jdk-25* \
            "${HOME:-}/opt"/graalvm* \
            "/usr/lib/jvm"/graalvm-jdk-25* \
            "/usr/lib/jvm"/graalvm* \
            "/opt"/graalvm-jdk-25* \
            "/opt"/graalvm*; do
            if [ -d "${candidate}" ] && [ -x "${candidate}/bin/native-image" ]; then
                GRAALVM_DIR="${candidate}"
                break
            fi
        done
    fi
fi
if [ -n "${GRAALVM_DIR}" ] && [ -d "${GRAALVM_DIR}" ]; then
    export GRAALVM_HOME="${GRAALVM_DIR}"
    export JAVA_HOME="${GRAALVM_DIR}"
    export PATH="${JAVA_HOME}/bin:${PATH}"
fi

echo "[ENV] Java version:"
java -version
echo "[ENV] Native Image version:"
native-image --version

BOOT_GEN="${1:-boot4}"
EXPECTED_MAJOR=65

MAVEN_DIR="${ROOT_DIR}/integration-tests/native/maven-${BOOT_GEN}-native"
GRADLE_DIR="${ROOT_DIR}/integration-tests/native/gradle-${BOOT_GEN}-native"

echo "[CONFIG] Target generation: ${BOOT_GEN} (expected bytecode major version: ${EXPECTED_MAJOR})"

APP_PID=""
cleanup() {
    if [ -n "${APP_PID}" ] && kill -0 "${APP_PID}" 2>/dev/null; then
        echo "[CLEANUP] Stopping native application process PID ${APP_PID}..."
        kill -15 "${APP_PID}" 2>/dev/null || true
        sleep 1
        kill -9 "${APP_PID}" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

wait_for_native_server() {
    local port="$1"
    local max_wait=30
    local count=0
    while ! curl -s "http://localhost:${port}/public" >/dev/null 2>&1; do
        sleep 0.2
        count=$((count + 1))
        if [ "${count}" -ge "$((max_wait * 5))" ]; then
            echo "[FAIL] Native server on port ${port} failed to start within ${max_wait}s!"
            return 1
        fi
    done
    return 0
}

# Step 1: Install reactor artifacts to mavenLocal
echo "[STEP 1] Building and publishing reactor artifacts to local repository..."
"${ROOT_DIR}/gradlew" publishToMavenLocal --no-daemon -q
"${ROOT_DIR}/mvnw" install -DskipTests -B -q
echo "[PASS] Reactor artifacts published locally."

# Step 2: Test Spring AOT & Viet Template AOT compilation for Maven fixture
echo "[STEP 2] Compiling Viet Template and Spring AOT for maven-${BOOT_GEN}-native..."
"${ROOT_DIR}/mvnw" clean test-compile spring-boot:process-aot -f "${MAVEN_DIR}/pom.xml" -B
echo "[PASS] Spring AOT processing succeeded for maven-${BOOT_GEN}-native."

# Step 3: Test Spring AOT & Viet Template AOT compilation for Gradle fixture
echo "[STEP 3] Compiling Viet Template and Spring AOT for gradle-${BOOT_GEN}-native..."
"${ROOT_DIR}/gradlew" clean processAot --project-dir "${GRADLE_DIR}" --no-daemon
echo "[PASS] Spring AOT processing succeeded for gradle-${BOOT_GEN}-native."

# Step 4: Compare templates.idx and generated .class files byte-for-byte parity
echo "[STEP 4] Comparing templates.idx and bytecode parity..."
MAVEN_IDX="${MAVEN_DIR}/target/classes/META-INF/viet-template/templates.idx"
GRADLE_IDX="${GRADLE_DIR}/build/generated/viet-template/resources/META-INF/viet-template/templates.idx"

if ! cmp -s "${MAVEN_IDX}" "${GRADLE_IDX}"; then
    echo "[FAIL] templates.idx differs between Maven and Gradle!"
    diff -u "${MAVEN_IDX}" "${GRADLE_IDX}"
    exit 1
fi
echo "[PASS] templates.idx byte-for-byte identical."

MAVEN_CLASSES="${MAVEN_DIR}/target/classes/io/github/minh124199/viettemplate/generated"
GRADLE_CLASSES="${GRADLE_DIR}/build/generated/viet-template/classes/io/github/minh124199/viettemplate/generated"

for maven_class in "${MAVEN_CLASSES}"/*.class; do
    class_name="$(basename "${maven_class}")"
    gradle_class="${GRADLE_CLASSES}/${class_name}"
    if [ ! -f "${gradle_class}" ]; then
        echo "[FAIL] Class ${class_name} generated by Maven but missing in Gradle!"
        exit 1
    fi
    if ! cmp -s "${maven_class}" "${gradle_class}"; then
        echo "[FAIL] Bytecode mismatch for ${class_name} between Maven and Gradle!"
        exit 1
    fi
    echo "[PASS] Bytecode identical for ${class_name}"
done

# Step 5: Verify classfile version
echo "[STEP 5] Verifying classfile version ${EXPECTED_MAJOR}..."
for class_file in "${MAVEN_CLASSES}"/*.class; do
    python3 -c "
import sys
with open('${class_file}', 'rb') as f:
    magic = f.read(4)
    if magic != b'\xca\xfe\xba\xbe':
        sys.exit(1)
    minor = int.from_bytes(f.read(2), 'big')
    major = int.from_bytes(f.read(2), 'big')
    if major != ${EXPECTED_MAJOR}:
        sys.exit(2)
"
    STATUS=$?
    if [ ${STATUS} -ne 0 ]; then
        echo "[FAIL] Class ${class_file} is not a valid classfile version ${EXPECTED_MAJOR}!"
        exit 1
    fi
done
echo "[PASS] All generated bytecode files are valid classfile version ${EXPECTED_MAJOR}."

# Step 6: Build Native Image executable with Maven
echo "[STEP 6] Building Maven GraalVM Native Image executable..."
"${ROOT_DIR}/mvnw" -Pnative native:compile -DskipTests -f "${MAVEN_DIR}/pom.xml" -B

MAVEN_NATIVE_BIN="${MAVEN_DIR}/target/spring-maven-${BOOT_GEN}-native"
if [ ! -f "${MAVEN_NATIVE_BIN}" ] || [ ! -x "${MAVEN_NATIVE_BIN}" ]; then
    echo "[FAIL] Native binary not found at ${MAVEN_NATIVE_BIN}!"
    exit 1
fi
echo "[PASS] Maven Native executable built successfully: ${MAVEN_NATIVE_BIN}"

# Step 7: Launch Native Image and run live HTTP tests
PORT=18080
echo "[STEP 7] Launching Maven Native Image binary on port ${PORT}..."
"${MAVEN_NATIVE_BIN}" --server.port="${PORT}" > /tmp/native-app-maven.log 2>&1 &
APP_PID=$!

wait_for_native_server "${PORT}"
echo "[PASS] Native application started and responding on port ${PORT}."

echo "[STEP 8] Executing live HTTP tests against Maven Native application..."

# 8.1 Public Endpoint
PUBLIC_RESP=$(curl -s "http://localhost:${PORT}/public")
echo "${PUBLIC_RESP}" | grep -q "Welcome, Alice!" || { echo "[FAIL] Missing user scalar rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Account: AliceAccount (Logins: 10)" || { echo "[FAIL] Missing record property rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Profile: Alice Wonderland" || { echo "[FAIL] Missing JavaBean getter rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Theme: dark" || { echo "[FAIL] Missing Map property rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Status: Veteran" || { echo "[FAIL] Missing #if conditional rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "<li>java</li>" || { echo "[FAIL] Missing #foreach loop rendering"; exit 1; }
echo "[PASS] Public endpoint rendered all model types (Record, JavaBean, Map, #if, #foreach) successfully."

# 8.2 Unauthenticated /dashboard -> 401 Unauthorized
DASH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${PORT}/dashboard")
if [ "${DASH_STATUS}" != "401" ] && [ "${DASH_STATUS}" != "302" ]; then
    echo "[FAIL] Unauthenticated /dashboard expected 401/302, got ${DASH_STATUS}"
    exit 1
fi
echo "[PASS] Unauthenticated access to /dashboard correctly protected (${DASH_STATUS})."

# 8.3 Authenticated /dashboard -> 200 OK + SecurityView & CsrfView
USER_DASH=$(curl -s -u user:user123 "http://localhost:${PORT}/dashboard")
echo "${USER_DASH}" | grep -q "user" || { echo "[FAIL] Missing authenticated principal name"; exit 1; }
echo "${USER_DASH}" | grep -q "true" || { echo "[FAIL] Missing authenticated status"; exit 1; }
echo "${USER_DASH}" | grep -q "false" || { echo "[FAIL] User unexpectedly has ROLE_ADMIN"; exit 1; }
echo "[PASS] Authenticated user dashboard rendered SecurityView correctly."

# 8.4 Role-based /admin authorization
USER_ADMIN_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u user:user123 "http://localhost:${PORT}/admin")
if [ "${USER_ADMIN_STATUS}" != "403" ]; then
    echo "[FAIL] User without ROLE_ADMIN expected 403 Forbidden on /admin, got ${USER_ADMIN_STATUS}"
    exit 1
fi
echo "[PASS] Role authorization enforced on native binary (403 Forbidden for non-admin)."

ADMIN_DASH=$(curl -s -u admin:admin123 "http://localhost:${PORT}/admin")
echo "${ADMIN_DASH}" | grep -q "admin" || { echo "[FAIL] Missing admin principal name"; exit 1; }
echo "${ADMIN_DASH}" | grep -q "true" || { echo "[FAIL] Missing admin authority confirmation"; exit 1; }
echo "[PASS] Admin dashboard rendered with full authority on native binary."

# Clean up Maven app process
kill -15 "${APP_PID}" 2>/dev/null || true
wait "${APP_PID}" 2>/dev/null || true
APP_PID=""
echo "[PASS] Maven Native executable tests completed successfully."

# Step 9: Build Native Image executable with Gradle
echo "[STEP 9] Building Gradle GraalVM Native Image executable..."
"${ROOT_DIR}/gradlew" nativeCompile --project-dir "${GRADLE_DIR}" --no-daemon

GRADLE_NATIVE_BIN="${GRADLE_DIR}/build/native/nativeCompile/spring-gradle-${BOOT_GEN}-native"
if [ ! -f "${GRADLE_NATIVE_BIN}" ] || [ ! -x "${GRADLE_NATIVE_BIN}" ]; then
    echo "[FAIL] Native binary not found at ${GRADLE_NATIVE_BIN}!"
    exit 1
fi
echo "[PASS] Gradle Native executable built successfully: ${GRADLE_NATIVE_BIN}"

# Step 10: Launch Gradle Native Image and run live HTTP tests
PORT=18081
echo "[STEP 10] Launching Gradle Native Image binary on port ${PORT}..."
"${GRADLE_NATIVE_BIN}" --server.port="${PORT}" > /tmp/native-app-gradle.log 2>&1 &
APP_PID=$!

wait_for_native_server "${PORT}"
echo "[PASS] Gradle Native application started and responding on port ${PORT}."

echo "[STEP 11] Executing live HTTP tests against Gradle Native application..."
PUBLIC_RESP=$(curl -s "http://localhost:${PORT}/public")
echo "${PUBLIC_RESP}" | grep -q "Welcome, Alice!" || { echo "[FAIL] Missing user scalar rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Account: AliceAccount (Logins: 10)" || { echo "[FAIL] Missing record property rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Profile: Alice Wonderland" || { echo "[FAIL] Missing JavaBean getter rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Theme: dark" || { echo "[FAIL] Missing Map property rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "Status: Veteran" || { echo "[FAIL] Missing #if conditional rendering"; exit 1; }
echo "${PUBLIC_RESP}" | grep -q "<li>java</li>" || { echo "[FAIL] Missing #foreach loop rendering"; exit 1; }
echo "[PASS] Gradle Public endpoint rendered all model types successfully."

USER_DASH=$(curl -s -u user:user123 "http://localhost:${PORT}/dashboard")
echo "${USER_DASH}" | grep -q "user" || { echo "[FAIL] Missing authenticated principal name"; exit 1; }
echo "${USER_DASH}" | grep -q "true" || { echo "[FAIL] Missing authenticated status"; exit 1; }
echo "[PASS] Gradle Authenticated user dashboard rendered SecurityView correctly."

ADMIN_DASH=$(curl -s -u admin:admin123 "http://localhost:${PORT}/admin")
echo "${ADMIN_DASH}" | grep -q "admin" || { echo "[FAIL] Missing admin principal name"; exit 1; }
echo "${ADMIN_DASH}" | grep -q "true" || { echo "[FAIL] Missing admin authority confirmation"; exit 1; }
echo "[PASS] Gradle Admin dashboard rendered with full authority on native binary."

kill -15 "${APP_PID}" 2>/dev/null || true
wait "${APP_PID}" 2>/dev/null || true
APP_PID=""

echo "=== ALL NATIVE IMAGE VERIFICATION CHECKS PASSED ==="
