package io.github.minh124199.viettemplate.vtl.engine.cache;

import io.github.minh124199.viettemplate.api.CompiledTemplate;
import io.github.minh124199.viettemplate.api.RenderContext;
import io.github.minh124199.viettemplate.api.TemplateException;
import io.github.minh124199.viettemplate.api.TemplateId;
import io.github.minh124199.viettemplate.api.TemplateOutput;
import io.github.minh124199.viettemplate.api.TemplateRenderException;
import io.github.minh124199.viettemplate.api.TemplateSecurityException;
import io.github.minh124199.viettemplate.language.vtl.ir.IrTemplate;
import io.github.minh124199.viettemplate.vtl.internal.compiler.TemplateClassLoader;
import java.io.IOException;
import java.util.Objects;
import java.util.Optional;

record AotExecutionTarget(
    CompiledTemplate compiledTemplate,
    Optional<TemplateClassLoader> classLoader,
    Optional<IrTemplate> irTemplate)
    implements ExecutionTarget {

  AotExecutionTarget {
    Objects.requireNonNull(compiledTemplate, "compiledTemplate must not be null");
    Objects.requireNonNull(classLoader, "classLoader must not be null");
    Objects.requireNonNull(irTemplate, "irTemplate must not be null");
  }

  @Override
  @SuppressWarnings("removal")
  public void render(RenderContext context, TemplateOutput output) throws IOException {
    try {
      compiledTemplate.render(context, output);
    } catch (VirtualMachineError | ThreadDeath fatal) {
      throw fatal;
    } catch (TemplateException te) {
      if (te.templateId().isPresent() && "<generated>".equals(te.templateId().get().value())) {
        TemplateId realId = resolveTemplateId();
        if (te instanceof TemplateRenderException tre) {
          throw new TemplateRenderException(
              rawMessage(tre), realId, tre.span(), tre.code().orElse(null), tre.getCause());
        }
        if (te instanceof TemplateSecurityException tse) {
          throw new TemplateSecurityException(
              rawMessage(tse), realId, tse.span(), tse.code().orElse(null), tse.getCause());
        }
      }
      throw te;
    }
  }

  private TemplateId resolveTemplateId() {
    try {
      return compiledTemplate.descriptor().id();
    } catch (AbstractMethodError ignored) {
      // Fallback if generated bytecode does not implement descriptor()
    }
    if (irTemplate.isPresent()) {
      return irTemplate.get().id();
    }
    try {
      java.lang.reflect.Method m = compiledTemplate.getClass().getMethod("id");
      return (TemplateId) m.invoke(compiledTemplate);
    } catch (ReflectiveOperationException ignored) {
      return TemplateId.of("<generated>");
    }
  }

  private static String rawMessage(TemplateException te) {
    String msg = te.getMessage();
    if (msg == null) {
      return null;
    }
    String marker = "<generated> - ";
    int idx = msg.indexOf(marker);
    return idx >= 0 ? msg.substring(idx + marker.length()) : msg;
  }
}
