package io.github.minh124199.viettemplate.tooling.maven;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class VietTemplateGenerateTypeScriptMojoTest {

  private static final String SAMPLE_SCHEMA =
      """
      {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "format": "viet-template-contract-schema/1",
        "schemaVersion": 1,
        "templateId": "order-view.vtl",
        "contractFingerprint": "abc123def456",
        "parameters": [
          {
            "name": "customer",
            "type": { "kind": "class", "name": "java.lang.String" },
            "nullable": true,
            "optional": false
          },
          {
            "name": "orderId",
            "type": { "kind": "primitive", "name": "long" },
            "nullable": false,
            "optional": false
          }
        ],
        "types": {}
      }
      """;

  @Test
  @DisplayName("Generates TypeScript declaration files (*.d.ts) from canonical schemas")
  void testGenerateTypeScript(@TempDir Path tempDir) throws Exception {
    Path schemaDir = tempDir.resolve("target/generated-resources/viet-template/schemas");
    Path tsOutputDir = tempDir.resolve("target/generated-sources/viet-template/typescript");
    Files.createDirectories(schemaDir);

    Files.writeString(
        schemaDir.resolve("order-view.vt-schema.json"), SAMPLE_SCHEMA, StandardCharsets.UTF_8);

    VietTemplateGenerateTypeScriptMojo mojo = new VietTemplateGenerateTypeScriptMojo();
    mojo.setSchemaDirectory(schemaDir.toFile());
    mojo.setTypeScriptOutputDirectory(tsOutputDir.toFile());

    assertThatCode(mojo::execute).doesNotThrowAnyException();

    Path dtsFile = tsOutputDir.resolve("order-view.d.ts");
    assertThat(dtsFile).isRegularFile();
    String dts = Files.readString(dtsFile, StandardCharsets.UTF_8);
    assertThat(dts).contains("// Generated by Viet Template M28.");
    assertThat(dts).contains("export interface TemplateParameters {");
    assertThat(dts).contains("customer: string | null;");
    assertThat(dts).contains("orderId: number;");
  }

  @Test
  @DisplayName("Skips execution when skip flag is set")
  void testSkipFlag(@TempDir Path tempDir) throws Exception {
    Path schemaDir = tempDir.resolve("target/generated-resources/viet-template/schemas");
    Path tsOutputDir = tempDir.resolve("target/generated-sources/viet-template/typescript");
    Files.createDirectories(schemaDir);

    Files.writeString(
        schemaDir.resolve("order-view.vt-schema.json"), SAMPLE_SCHEMA, StandardCharsets.UTF_8);

    VietTemplateGenerateTypeScriptMojo mojo = new VietTemplateGenerateTypeScriptMojo();
    mojo.setSchemaDirectory(schemaDir.toFile());
    mojo.setTypeScriptOutputDirectory(tsOutputDir.toFile());
    mojo.setSkip(true);

    assertThatCode(mojo::execute).doesNotThrowAnyException();
    assertThat(tsOutputDir).doesNotExist();
  }

  @Test
  @DisplayName("Skips gracefully when schema directory does not exist")
  void testNonExistentSchemaDirectory(@TempDir Path tempDir) {
    Path schemaDir = tempDir.resolve("non-existent-schemas");
    Path tsOutputDir = tempDir.resolve("target/generated-sources/viet-template/typescript");

    VietTemplateGenerateTypeScriptMojo mojo = new VietTemplateGenerateTypeScriptMojo();
    mojo.setSchemaDirectory(schemaDir.toFile());
    mojo.setTypeScriptOutputDirectory(tsOutputDir.toFile());

    assertThatCode(mojo::execute).doesNotThrowAnyException();
    assertThat(tsOutputDir).doesNotExist();
  }

  @Test
  @DisplayName("Preserves nested directory structure based on templateId")
  void testNestedSchemaDirectory(@TempDir Path tempDir) throws Exception {
    Path schemaDir = tempDir.resolve("target/generated-resources/viet-template/schemas");
    Path tsOutputDir = tempDir.resolve("target/generated-sources/viet-template/typescript");
    Path nestedSchemaDir = schemaDir.resolve("users/reports");
    Files.createDirectories(nestedSchemaDir);

    String nestedSchema =
        """
        {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "format": "viet-template-contract-schema/1",
          "schemaVersion": 1,
          "templateId": "users/reports/summary.vtl",
          "contractFingerprint": "nested123",
          "parameters": [
            {
              "name": "title",
              "type": { "kind": "class", "name": "java.lang.String" },
              "nullable": false,
              "optional": false
            }
          ],
          "types": {}
        }
        """;

    Files.writeString(
        nestedSchemaDir.resolve("summary.vt-schema.json"), nestedSchema, StandardCharsets.UTF_8);

    VietTemplateGenerateTypeScriptMojo mojo = new VietTemplateGenerateTypeScriptMojo();
    mojo.setSchemaDirectory(schemaDir.toFile());
    mojo.setTypeScriptOutputDirectory(tsOutputDir.toFile());

    assertThatCode(mojo::execute).doesNotThrowAnyException();

    Path dtsFile = tsOutputDir.resolve("users/reports/summary.d.ts");
    assertThat(dtsFile).isRegularFile();
    String dts = Files.readString(dtsFile, StandardCharsets.UTF_8);
    assertThat(dts).contains("title: string;");
  }

  @Test
  @DisplayName("Cleans up stale .d.ts files when corresponding schema is deleted")
  void testStaleFileCleanup(@TempDir Path tempDir) throws Exception {
    Path schemaDir = tempDir.resolve("target/generated-resources/viet-template/schemas");
    Path tsOutputDir = tempDir.resolve("target/generated-sources/viet-template/typescript");
    Files.createDirectories(schemaDir);
    Files.createDirectories(tsOutputDir);

    // Create a stale .d.ts file that has no corresponding schema
    Path staleFile = tsOutputDir.resolve("old-template.d.ts");
    Files.writeString(staleFile, "// stale", StandardCharsets.UTF_8);

    // Create an active schema
    Files.writeString(
        schemaDir.resolve("order-view.vt-schema.json"), SAMPLE_SCHEMA, StandardCharsets.UTF_8);

    VietTemplateGenerateTypeScriptMojo mojo = new VietTemplateGenerateTypeScriptMojo();
    mojo.setSchemaDirectory(schemaDir.toFile());
    mojo.setTypeScriptOutputDirectory(tsOutputDir.toFile());

    assertThatCode(mojo::execute).doesNotThrowAnyException();

    assertThat(tsOutputDir.resolve("order-view.d.ts")).isRegularFile();
    assertThat(staleFile).doesNotExist();
  }

  @Test
  @DisplayName("Generates TypeScript declaration files (*.d.ts) from JSON Schemas (*.schema.json)")
  void testGenerateTypeScriptFromJsonSchema(@TempDir Path tempDir) throws Exception {
    Path schemaDir = tempDir.resolve("target/generated-resources/viet-template/schemas");
    Path tsOutputDir = tempDir.resolve("target/generated-sources/viet-template/typescript");
    Files.createDirectories(schemaDir);

    String jsonSchema =
        """
        {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "$id": "user-account.vtl",
          "type": "object",
          "properties": {
            "account": {
              "type": "object",
              "properties": {
                "username": { "type": "string" },
                "balance": { "type": "number" },
                "notes": { "type": ["string", "null"] }
              },
              "required": ["username", "balance"]
            }
          },
          "required": ["account"]
        }
        """;

    Files.writeString(
        schemaDir.resolve("user-account.schema.json"), jsonSchema, StandardCharsets.UTF_8);

    VietTemplateGenerateTypeScriptMojo mojo = new VietTemplateGenerateTypeScriptMojo();
    mojo.setSchemaDirectory(schemaDir.toFile());
    mojo.setTypeScriptOutputDirectory(tsOutputDir.toFile());

    assertThatCode(mojo::execute).doesNotThrowAnyException();

    Path dtsFile = tsOutputDir.resolve("user-account.d.ts");
    assertThat(dtsFile).isRegularFile();
    String dts = Files.readString(dtsFile, StandardCharsets.UTF_8);
    assertThat(dts).contains("// Generated by Viet Template M28.");
    assertThat(dts).contains("export interface TemplateParameters {");
    assertThat(dts).contains("account: Account;");
    assertThat(dts).contains("export interface Account {");
    assertThat(dts).contains("balance: number;");
    assertThat(dts).contains("notes?: string | null;");
    assertThat(dts).contains("username: string;");
  }
}
